
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer
{

using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;

    public partial class AuctionLogs
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public int AuctionId { get; set; }

    public System.DateTime DateTime { get; set; }

    public byte TypeBid { get; set; }

    public Nullable<int> Price { get; set; }


        [ScriptIgnore]
        public virtual Auction Auction { get; set; }
        [ScriptIgnore]
        public virtual User User { get; set; }

}

}
