
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Brand { get; set; }

    public Nullable<byte> Model_Year { get; set; }

    public int Price { get; set; }

    public Nullable<bool> Img { get; set; }



    public virtual Auction Auction { get; set; }

}

}
